name: Call Slack Webhook

on:
  workflow_dispatch:
  schedule:
    - cron: '35 9 * * 1-5'

jobs:
  check-holiday-jp:
    runs-on: ubuntu-latest
    outputs:
      is-holiday: ${{ steps.check-holiday.outputs['is-holiday'] }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install @holiday-jp/holiday_jp
      - id: check-holiday
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const { holidayJp } = require('@holiday-jp/holiday_jp');
            const today = new Date();
            console.log(today);
            const isHoliday = holidayJp.isHoliday(today);
            console.log(isHoliday);
            core.setOutput('is-holiday', isHoliday.toString());

  make-call:
    runs-on: ubuntu-latest
    needs: check-holiday-jp
    if: needs.check-holiday-jp.outputs.is-holiday == 'false' && github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.2
      
      - name: build
        run: go build -o app main.go

      - name: checkout mizubotprivate repo
        uses: actions/checkout@v3
        with:
          repository: mizumoto-cn/mizubotprivate
          path: ./mizubotprivate
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: run
        run: |
            ./app -webhook-url ${{ secrets.SLACK_WEBHOOK_URL }} -tmp ./mizubotprivate/template/tmp.txt -to-mizumoto "" \
            -content ./mizubotprivate/template/content.txt -chan1 ${{ secrets.SLACK_CHANNEL_1 }} -user1mail ${{ secrets.SLACK_USER_MAIL_1 }}

  after_report:
    if: github.event_name == 'schedule'
    uses: ./.github/workflows/after-report.yml
